# AI: below section was generated by an AI
# Clock dashboard for a 128x32 WLED HUB75 matrix.
# Weather observations for 04451/Borsdorf are DWD data provided by Bright Sky.
$wledUri = "http://192.168.178.214/json/state"
$weatherUri = "https://api.brightsky.dev/current_weather?lat=51.35&lon=12.53333"

try {
  $weatherResponse = Invoke-RestMethod `
    -Uri $weatherUri `
    -Method Get `
    -TimeoutSec 15 `
    -ErrorAction Stop

  if ($null -eq $weatherResponse.weather.temperature) {
    throw "Die Wetterstation hat keinen Temperaturwert geliefert."
  }

  $temperature = [double]$weatherResponse.weather.temperature
  $temperatureText = $temperature.ToString("0.0", [Globalization.CultureInfo]::InvariantCulture)

  $germanCulture = [Globalization.CultureInfo]::GetCultureInfo("de-DE")
  $weekday = (Get-Date).ToString("dddd", $germanCulture)
  $weekday = $germanCulture.TextInfo.ToTitleCase($weekday)
}
catch {
  Write-Error "Anzeigedaten konnten nicht geladen werden: $($_.Exception.Message)"
  exit 1
}

if ($temperature -lt 5) {
  $temperatureColor = @(40, 120, 255)
}
elseif ($temperature -lt 20) {
  $temperatureColor = @(40, 255, 120)
}
elseif ($temperature -lt 28) {
  $temperatureColor = @(255, 150, 20)
}
else {
  $temperatureColor = @(255, 40, 20)
}

function New-TextSegment {
  param(
    [int]$Id,
    [int]$Start,
    [int]$Stop,
    [int]$StartY,
    [int]$StopY,
    [string]$Text,
    [int]$FontSize,
    [int[]]$Color
  )

  return @{
    id = $Id
    start = $Start
    stop = $Stop
    startY = $StartY
    stopY = $StopY
    fx = 122
    n = $Text
    sx = 220
    ix = 128
    c1 = 0
    c2 = $FontSize
    pal = 0
    col = @(
      ,$Color
      ,@(0, 0, 0)
      ,@(0, 0, 0)
    )
  }
}

function New-LineSegment {
  param(
    [int]$Id,
    [int]$Start,
    [int]$Stop,
    [int]$StartY,
    [int]$StopY,
    [int[]]$Color
  )

  return @{
    id = $Id
    start = $Start
    stop = $Stop
    startY = $StartY
    stopY = $StopY
    fx = 0
    pal = 0
    col = @(
      ,$Color
      ,@(0, 0, 0)
      ,@(0, 0, 0)
    )
  }
}

$segments = @(
  # Large clock with one free pixel above and below the horizontal divider.
  New-TextSegment 0 0 128 0 15 "#HHMM0" 255 @(255, 220, 140)

  # Lower information row: weekday, date, and temperature.
  New-TextSegment 1 0 42 18 32 $weekday 128 @(210, 80, 255)
  New-TextSegment 2 45 84 18 32 "#DATE0" 128 @(40, 200, 255)
  New-TextSegment 3 87 128 18 32 "$temperatureText C" 128 $temperatureColor

  # Decorative separators with a free pixel on either side.
  New-LineSegment 4 0 128 16 17 @(30, 100, 220)
  New-LineSegment 5 43 44 18 32 @(100, 40, 180)
  New-LineSegment 6 85 86 18 32 @(100, 40, 180)
)

# Remove segments left over by another dashboard to prevent overlaps.
try {
  $currentState = Invoke-RestMethod -Uri $wledUri -Method Get -TimeoutSec 8 -ErrorAction Stop
  $obsoleteIds = @($currentState.seg | Where-Object { $_.id -ge 7 } | ForEach-Object { [int]$_.id })

  for ($offset = 0; $offset -lt $obsoleteIds.Count; $offset += 8) {
    $last = [math]::Min($offset + 7, $obsoleteIds.Count - 1)
    $deletions = @($obsoleteIds[$offset..$last] | ForEach-Object { @{ id = $_; stop = 0 } })
    $deleteBody = @{ transition = 0; seg = $deletions } | ConvertTo-Json -Depth 4 -Compress
    Invoke-RestMethod `
      -Uri $wledUri `
      -Method Post `
      -ContentType "application/json" `
      -Body $deleteBody `
      -ErrorAction Stop | Out-Null
  }

  $body = @{
    on = $true
    transition = 0
    seg = $segments
  } | ConvertTo-Json -Depth 7 -Compress

  Invoke-RestMethod `
    -Uri $wledUri `
    -Method Post `
    -ContentType "application/json" `
    -Body $body `
    -ErrorAction Stop | Out-Null
}
catch {
  Write-Error "WLED konnte nicht aktualisiert werden: $($_.Exception.Message)"
  exit 1
}

Write-Host "Uhrzeit: #HHMM0"
Write-Host "Wochentag: $weekday"
Write-Host "Datum: #DATE0"
Write-Host "Temperatur: $temperatureText C"
Write-Host "Clock-Dashboard wurde an WLED gesendet."
# AI: end
